### ISSUE TITLE
Input data for dining hall

### ISSUE THREAD

**Issue by demyinn00** [UCSDFoodReview/UCSDFoodReview#24]
- [ ] Input all 10 dining halls: Name, image, and description
1. - [x] CV
2. - [x] Cafe Ventanas 
3. - [x] 64 Degrees
4. - [x] Ocean View
5. - [x] Pines
6. - [x] 6th
7. - [x] Club Med
8. - [x] Bistro
9. - [x] Roots
10. - [x] Foodworx

**Comment by demyinn00** [comment]
I will do 1-3

**Comment by demyinn00** [comment]
@hoatuyet423 will do 4-7

**Comment by hoatuyet423** [comment]
I will do 4-7

**Comment by johnxminimo** [comment]
Working on:
8. Bistro
9. Roots
10. Foodworx

**Comment by demyinn00** [comment]
Completed 1-3. When you two get a chance, please get these in so that when @brianliu1412 finishes the dining hall view skeleton, I can start implementing the code to populate it :)

**Comment by hoatuyet423** [comment]
completed 4-7

**Comment by johnxminimo** [comment]
Completed 8-10.
