### ISSUE TITLE
Input data for restaurants

### ISSUE THREAD

**Issue by demyinn00** [UCSDFoodReview/UCSDFoodReview#25]
- [ ] Input as many restaurants that we can find: dining hall pointer, name of restaurant
1. - [x] CV
2. - [x] Cafe Ventanas 
3. - [x] 64 Degrees
4. - [x] Ocean View
5. - [x] Pines
6. - [x] 6th
7. - [x] Club Med
8. - [x] Bistro
9. - [x] Roots
10. - [x] Foodworx

**Comment by demyinn00** [comment]
I added the restaurants for CV, Cafe Ventanas, and 64

**Comment by hoatuyet423** [comment]
I'm done for 4-7

**Comment by johnxminimo** [comment]
Completed 8-10.
